// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createStatement = `-- name: CreateStatement :exec
INSERT INTO STATEMENTS(TXN_TYPE, AMOUNT, TAG, DESCRIPTION) VALUES(?, ?, ?, ?) RETURNING id, txn_type, amount, tag, description, created_at, updated_at
`

type CreateStatementParams struct {
	TxnType     sql.NullString
	Amount      sql.NullInt64
	Tag         sql.NullString
	Description sql.NullString
}

func (q *Queries) CreateStatement(ctx context.Context, arg CreateStatementParams) error {
	_, err := q.db.ExecContext(ctx, createStatement,
		arg.TxnType,
		arg.Amount,
		arg.Tag,
		arg.Description,
	)
	return err
}

const getAllStatements = `-- name: GetAllStatements :many
SELECT id, txn_type, amount, tag, description, created_at, updated_at FROM STATEMENTS
`

func (q *Queries) GetAllStatements(ctx context.Context) ([]Statement, error) {
	rows, err := q.db.QueryContext(ctx, getAllStatements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Statement
	for rows.Next() {
		var i Statement
		if err := rows.Scan(
			&i.ID,
			&i.TxnType,
			&i.Amount,
			&i.Tag,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllStatementsPaginated = `-- name: GetAllStatementsPaginated :many
SELECT id, txn_type, amount, tag, description, created_at, updated_at
FROM STATEMENTS
ORDER BY CREATED_AT DESC
LIMIT 10 OFFSET ?
`

func (q *Queries) GetAllStatementsPaginated(ctx context.Context, offset int64) ([]Statement, error) {
	rows, err := q.db.QueryContext(ctx, getAllStatementsPaginated, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Statement
	for rows.Next() {
		var i Statement
		if err := rows.Scan(
			&i.ID,
			&i.TxnType,
			&i.Amount,
			&i.Tag,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatementsByTag = `-- name: GetStatementsByTag :many
SELECT id, txn_type, amount, tag, description, created_at, updated_at FROM STATEMENTS WHERE TAG = ?
`

func (q *Queries) GetStatementsByTag(ctx context.Context, tag sql.NullString) ([]Statement, error) {
	rows, err := q.db.QueryContext(ctx, getStatementsByTag, tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Statement
	for rows.Next() {
		var i Statement
		if err := rows.Scan(
			&i.ID,
			&i.TxnType,
			&i.Amount,
			&i.Tag,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatementsCount = `-- name: GetStatementsCount :one
SELECT COUNT(*) FROM STATEMENTS
`

func (q *Queries) GetStatementsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getStatementsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getStatementsLimit = `-- name: GetStatementsLimit :many
SELECT id, txn_type, amount, tag, description, created_at, updated_at FROM STATEMENTS LIMIT ?
`

func (q *Queries) GetStatementsLimit(ctx context.Context, limit int64) ([]Statement, error) {
	rows, err := q.db.QueryContext(ctx, getStatementsLimit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Statement
	for rows.Next() {
		var i Statement
		if err := rows.Scan(
			&i.ID,
			&i.TxnType,
			&i.Amount,
			&i.Tag,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
