CREATE TABLE IF NOT EXISTS STATEMENTS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	TXN_TYPE TEXT,
	AMOUNT INT,
	TAG TEXT,
	DESCRIPTION TEXT,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);
